apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tekton-go-shared-tasks 
  janus-idp.io/tekton: tekton-go-shared-tasks
  backstage.io/kubernetes-id: tekton-go-shared-tasks
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tekton-go-shared-tasks
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml