apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tekton-go-shared-tasks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-go-shared-tasks 
  name: tekton-go-shared-tasks
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tekton-go-shared-tasks 
